config_setting (
    name = "linux",
    values = {"cpu" : "linux"},
    visibility = ["//visibility:public"]
)

LINKOPTS = [
    "-lpthread",
    "-ldl"
]

cc_binary(
    name = "jz22",
    srcs = [ "jz22.cpp"],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz24",
    srcs = [ "jz24.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz18",
    srcs = [ "jz18.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz6",
    srcs = [ "jz6.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz76",
    srcs = [ "jz76.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz23",
    srcs = [ "jz23.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz25",
    srcs = [ "jz25.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz35",
    srcs = [ "jz35.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)


cc_binary(
    name = "jz52",
    srcs = [ "jz52.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz55",
    srcs = [ "jz55.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz27",
    srcs = [ "jz27.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz68",
    srcs = [ "jz68.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz86",
    srcs = [ "jz86.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz28",
    srcs = [ "jz28.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz82",
    srcs = [ "jz82.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz34",
    srcs = [ "jz34.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz54",
    srcs = [ "jz54.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz79",
    srcs = [ "jz79.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz33",
    srcs = [ "jz33.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)
