config_setting (
    name = "linux",
    values = {"cpu" : "linux"},
    visibility = ["//visibility:public"]
)

LINKOPTS = [
    "-lpthread",
    "-ldl"
]

cc_binary(
    name = "jz22",
    srcs = [ "jz22.cpp"],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz24",
    srcs = [ "jz24.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz18",
    srcs = [ "jz18.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz6",
    srcs = [ "jz6.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz76",
    srcs = [ "jz76.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)

cc_binary(
    name = "jz23",
    srcs = [ "jz23.cpp" ],
    deps = [
    ],
    linkopts = LINKOPTS
)
